# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {U:/Lab 9/Egg_timer/Egg_timer.cache/wt} [current_project]
set_property parent.project_path {U:/Lab 9/Egg_timer/Egg_timer.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo {u:/Lab 9/Egg_timer/Egg_timer.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet {{u:/Lab 9/Egg_timer/Egg_timer.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp}}
set_property used_in_implementation false [get_files {{u:/Lab 9/Egg_timer/Egg_timer.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp}}]
read_verilog -library xil_defaultlib {
  {U:/Lab 9/Egg_timer/Egg_timer.srcs/sources_1/new/bcdto7segment_display.v}
  {U:/Lab 9/Egg_timer/Egg_timer.srcs/sources_1/imports/new/bcdto7segment_dataflow.v}
  {U:/Lab 9/Egg_timer/Egg_timer.srcs/sources_1/imports/new/dynamic_display.v}
  {U:/Lab 9/Egg_timer/Egg_timer.srcs/sources_1/new/count_down.v}
  {U:/Lab 9/Egg_timer/Egg_timer.srcs/sources_1/new/Up_pulse.v}
  {U:/Lab 9/Egg_timer/Egg_timer.srcs/sources_1/imports/new/debounce.v}
  {U:/Lab 9/Egg_timer/Egg_timer.srcs/sources_1/new/clk_1_sec.v}
  {U:/Lab 9/Egg_timer/Egg_timer.srcs/sources_1/new/Egg_timer.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{U:/Lab 9/Egg_timer/Egg_timer.srcs/constrs_1/imports/Egg_timer/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{U:/Lab 9/Egg_timer/Egg_timer.srcs/constrs_1/imports/Egg_timer/Nexys4DDR_Master.xdc}}]


synth_design -top Egg_timer -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Egg_timer.dcp

catch { report_utilization -file Egg_timer_utilization_synth.rpt -pb Egg_timer_utilization_synth.pb }
